### ISSUE TITLE
dnn_dcgan_ex.cpp is missing.

### ISSUE THREAD

**Issue by newforrestgump001** [intellizd/dlib-dcgan_example#1]
CMake Error at CMakeLists.txt:96 (add_executable):
  Cannot find source file:
   dnn_dcgan_ex.cpp

**Comment by newforrestgump001** [comment]
after change the filename in CMakeLists.txt and some other modifications, it builds in ubuntu! Thanks a lot!

**Comment by intellizd** [comment]
@newforrestgump001 Thank you for pointing out the problem. I'll fix it and upload it!

**Comment by newforrestgump001** [comment]
You're welcome! Thank you for your great work!
